language: node_js
node_js:
  - "stable"

sudo: required

cache:
  yarn: true
  directories:
    - node_modules
    - client/node_modules

install:
  - yarn install-deps

before_script:
  - yarn build

script:
  - yarn test
