language: node_js
node_js:
  - "stable"

sudo: required

notifications:
  email:
    on_success: never

cache:
  yarn: true
  directories:
    - node_modules
    - client/node_modules

install:
  - yarn install-deps

before_script:
  - yarn build

script:
  - yarn test
