language: node_js
node_js:
  - stable
sudo: required
notifications:
  email:
    on_success: never
cache:
  yarn: true
  directories:
    - node_modules
env:
  - NODE_ENV=production
addons:
  chrome: stable
install:
  - yarn install-deps
before_script:
  - yarn build
script:
  - yarn lint
  - yarn start &
  - yarn start:client &
  - sleep 15
  - yarn test
deploy:
  provider: heroku
  app: pacific-hollows-74267
  api_key:
    secure: ruuywISE+bZyRiBsLYrQmyMOzGvBs8uz/E+2/+K9xM20T8VwskRz7fpkmkrUrbrK+YzL74NOHeCmIunEzmmOYMlnHFVN8MztuGQDwnsk2AdHzlQx3DZU9LbiMSZ2PTtcJ8q6Cb5xlJew2XQttyXaZCWZbjfOdpy06HMIj/IY7s2Vp66p36Mhm+9FiV7DNQot/NKXlhP9cSy+o6iAvg8IcsjRe2rPhoQ/k3P0mSJg78ymvDpLj1aeGo6GjfDKVEI1O1WrH37Y8R7JKzrroxrXyZqTvfVd0Ndd4ZFkw76JvXLdyVNNe+Zrc2rLGZPQgp9b2QdMSz+k2JPtbg31C2J4bqFKF/NXQof0zRN237zu89dfnurpZFZgxLpcg3iuEBXyBR6s+RTOqHZkyhE6AjFACVXqYGnmJMQ5Q8n+vfGrf9LmxepIGbumWmP7CGfovLdCWYosQ+vvu4orkBGcyYRiTfqodr8QFO+JX+eqPD94WfD53+uJmteboVkbfPX9x7g+44bDJdZLKmCIhP1NDZJtOlaTV44MEuvkEIEAGh6beNulyqD5K9CZRnQsgMpaCP400hq41LIOV/03o0VJ1g/zQZD1hNo//kf+idJ83VoeCLbqBERMSgHXASJvpLPHmxdFnpAQQNCfWNzVRDuVcppHCDenMk5ec58wUTl/qsykCgc=
