language: node_js
node_js:
  - "stable"

sudo: required

cache:
  yarn: true
  directories:
    - node_modules
    - client/node_modules

before_install:
  - npm install -g yarn --cache-min 999999999

install:
  - yarn install

before_script:
  - yarn build

script:
  - yarn test
